---
title: "Pitching"
author: "Tim Potter"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(knitr)
library(readr)
library(ggplot2)
library(ggrepel)
library(stringr)

pitchers <- read_csv("pitcher-data.csv")

pitchers <- pitchers %>%
  select(-Pit, -Str) %>%
  drop_na()

pitchers <- pitchers %>%
  mutate(Year_ch = as.character(pitchers$Year))
         
for (i in pitchers$Rk){
  name <- str_split(pitchers[i,2], "-")[[1]]
  
  pitchers[i,2] <- str_c(name[1],pitchers[i,48], sep = " ")
}

pitchers <- pitchers %>%
  mutate(Player.f = as.factor(pitchers$Player))

pitchers$Player.f <- factor(pitchers$Player.f, levels = pitchers$Player.f[order(pitchers$`W-L%`)])

theme_set(theme_bw())
```

```{r, fig.width=12, fig.height=10}
theme_set(theme_light())
pitchers %>%
  filter(`W-L%` < 0.5) %>%
  ggplot(aes(x = ERA, y = `W-L%`, label = Player)) + 
  geom_point(size = 2) +
  geom_label_repel(data = subset(pitchers, `W-L%` < 0.34), fill = 'cyan') +
  geom_label_repel(data = subset(pitchers, ERA < 2.25), fill = 'coral') +
  ylab("Winning Percentage") +
  ggtitle("Every Qualified Season Since 1968 with an ERA Below 3.00 and More Losses than Wins") +
  labs(caption = "Data from Baseball-Reference") +
  theme(plot.title = element_text(hjust = 0.5)) 

theme_set(theme_gray())
pitchers %>%
  filter(`W-L%` < 0.5) %>%
  ggplot(aes(x = Player.f,y = `W-L%`, fill = ERA)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ylab("Winning Percentage") +
  xlab("Player") +
  ggtitle("Pitchers with an ERA Below 3.00 
          and a Winning Percentage Below 0.5 in a Season") +
  scale_fill_gradient(low = 'red', high = 'black') +
  coord_flip(ylim=c(0.3,0.5)) +
  labs(caption = "Players who qualified for ERA Title, since 1968.
       Data from Baseball-Reference") +
  theme(plot.title = element_text(hjust = 0.5)) 
```